// skillIconMap.js
const Z_SkillIconMap = {
  "C": "devicon-c-plain",
  "C++": "devicon-cplusplus-plain",
  "Python": "devicon-python-plain",
  "Go": "devicon-go-plain",
  "Golang": "devicon-go-plain",
  "Rust": "devicon-rust-plain",
  "Java": "devicon-java-plain",
  "JavaScript": "devicon-javascript-plain",
  "TypeScript": "devicon-typescript-plain",
  "React": "devicon-react-original",
  "Vue": "devicon-vuejs-plain",
  "Node.js": "devicon-nodejs-plain",
  "HTML": "devicon-html5-plain",
  "HTML5": "devicon-html5-plain",
  "CSS": "devicon-css3-plain",
  "CSS3": "devicon-css3-plain",
  "Git": "devicon-git-plain",
  "GitHub": "devicon-github-original",
  "Linux": "devicon-linux-plain",
  "Docker": "devicon-docker-plain",
  "MySQL": "devicon-mysql-plain",
  "PostgreSQL": "devicon-postgresql-plain",
  "MongoDB": "devicon-mongodb-plain",
  "Redis": "devicon-redis-plain",
  "Nginx": "devicon-nginx-plain",
  "Kubernetes": "devicon-kubernetes-plain",
  "AWS": "devicon-amazonwebservices-plain",
  "Azure": "devicon-azure-plain",
  "GCP": "devicon-googlecloud-plain",
  "PHP": "devicon-php-plain",
  "Swift": "devicon-swift-plain",
  "Kotlin": "devicon-kotlin-plain",
  "Dart": "devicon-dart-plain",
  "Flutter": "devicon-flutter-plain",
  "Android": "devicon-android-plain",
  "Apple": "devicon-apple-original",
  "iOS": "devicon-apple-original",
  "Unity": "devicon-unity-original",
  "Unreal": "devicon-unrealengine-original",
};

export default Z_SkillIconMap;
